### ISSUE TITLE
Parser fails, zero length field name in format

### ISSUE THREAD

**Issue by adaviel** [KimBurgess/zero-log-parser#7]
python-2.6.6 on CentOS 6, 2017 Zero FXS

./zero_log_parser-orig.py 538XXBZ48HCJ08346_MBB_2017-11-04.bin
  File "./zero_log_parser-orig.py", line 569, in <module>
    parse_log(log_file, output_file)
  File "./zero_log_parser-orig.py", line 500, in parse_log
    print('Parsing {}...'.format(bin_file))
ValueError: zero length field name in format

I note that my VIN is at offset 0x252 and bike model at 0x26c

**Comment by kimburgess** [comment]
Thanks for the issue!

Unfortunately I'm no longer maintaining this tool as I parted ways with my Zero. There's an active fork over here though: https://github.com/zero-motorcycle-community/zero-log-parser.
